apiVersion: v1
kind: Secret
metadata:
  name: todoist-secrets
  namespace: todoist-dev
  labels:
    app.kubernetes.io/name: todoist-secrets
    environment: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres.todoist-dev.svc.cluster.local:5432/todoist_dev?schema=public"
  JWT_SECRET: "dev-insecure-development-jwt-secret-min-32-chars-long"
  AI_API_KEY: "mock-dev-key"
