apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/hpa.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - ai/deployment.yaml
  - ai/service.yaml
  - ai/hpa.yaml
  - migrations/job.yaml
  - ingress/ingress.yaml
