apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app.kubernetes.io/name: ai
    app.kubernetes.io/component: ai-service
    app.kubernetes.io/part-of: todoist-application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai
    app.kubernetes.io/component: ai-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
