apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todoist-staging

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/ingress-patch.yaml
  - path: patches/configmap-patch.yaml
  - path: patches/web-replicas.yaml
  - path: patches/backend-replicas.yaml
  - path: patches/ai-replicas.yaml
